export default Object.freeze({
  SCENARIOS_FETCHING: 'SCENARIOS_FETCHING',
  SCENARIOS_FETCHED: 'SCENARIOS_FETCHED',
  SCENARIOS_FETCH_FAILED: 'SCENARIOS_FETCH_FAILED',

  SCENARIO_FETCHING: 'SCENARIO_FETCHING',
  SCENARIO_FETCHED: 'SCENARIO_FETCHED',
  SCENARIO_FETCH_FAILED: 'SCENARIO_FETCH_FAILED',

  SCENARIO_CREATING: 'SCENARIO_CREATING',
  SCENARIO_CREATED: 'SCENARIO_CREATED',
  SCENARIO_CREATE_FAILED: 'SCENARIO_CREATE_FAILED',

  SCENARIO_UPDATING: 'SCENARIO_UPDATING',
  SCENARIO_UPDATED: 'SCENARIO_UPDATED',
  SCENARIO_UPDATE_FAILED: 'SCENARIO_UPDATE_FAILED',

  SCENARIO_DELETING: 'SCENARIO_DELETING',
  SCENARIO_DELETED: 'SCENARIO_DELETED',
  SCENARIO_DELETE_FAILED: 'SCENARIO_DELETE_FAILED',

  RUN_SCENARIO_FETCHING: 'RUN_SCENARIO_FETCHING',
  RUN_SCENARIO_FETCHED: 'RUN_SCENARIO_FETCHED',
  RUN_SCENARIO_FETCH_FAILED: 'RUN_SCENARIO_FETCH_FAILED',

  SCENARIO_RESULTS_FETCHING: 'SCENARIO_RESULTS_FETCHING',
  SCENARIO_RESULTS_FETCHED: 'SCENARIO_RESULTS_FETCHED',
  SCENARIO_RESULTS_FETCH_FAILED: 'SCENARIO_RESULTS_FETCH_FAILED',
})
