export default Object.freeze({
  SCENARIOS_FETCHING: 'SCENARIOS_FETCHING',
  SCENARIOS_FETCHED: 'SCENARIOS_FETCHED',
  SCENARIOS_FETCH_FAILED: 'SCENARIOS_FETCH_FAILED',

  RUN_SCENARIO_FETCHING: 'RUN_SCENARIO_FETCHING',
  RUN_SCENARIO_FETCHED: 'RUN_SCENARIO_FETCHED',
  RUN_SCENARIO_FETCH_FAILED: 'RUN_SCENARIO_FETCH_FAILED',
})