apiVersion: urth.sre-norns.com/v1
kind: runners
metadata:
  name: "example-runner-yaml"
  labels:
    env: "dev" 
    nature: "test-runner"
spec:
  active: true
  description: "A runner resource example"
  jobRequirements:
    probeKinds: [tcp, http]
    maxDuration: 1m
  workerRequirements:
    minDuration: 1ns
    maxDuration: 1m
  propagatedLabels:
    env: dev
