apiVersion: v1
kind: runners
metadata:
  name: "example-runner-yaml"
  labels: 
    os: "linux"
    cloud_self: aws
spec:
  active: true
  description: "A runner resource"
  requirements:
    matchSelector:
      - { "key": "urth/capability.prob.tcp", "operator":"NotIn"}
      - { "key": "urth/capability.prob.http", "operator":"NotIn"}
      - { "key": "urth/capability.prob.har", "operator":"NotIn"}
      - { "key": "urth/capability.prob.puppeteer", "operator":"NotIn"}
