apiVersion: v1
kind: scenarios
metadata:
  name: basic-rest-self-prober-http
  labels:
    app: web-prob
    function: front-end
spec:
  description: "HTTP prober checking api/version every 5 minutes"
  active: true
  schedule: "@5minutes"
  requirements:
    matchLabels:
      os: "linux"
    matchSelector:
      - { key: "envX", operator: "NotIn",  values: ["dev", "testing"] }
  prob:
    kind: rest
    spec:
      script: |
        # @name Get HTTPBin
        GET https://httpbin.org/get
        Accept: application/json
