apiVersion: v1
kind: scenarios
metadata:
  name: basic-rest-self-prober-http
  labels:
    app: web-prob
    function: front-end
spec:
  description: "HTTP prober checking api/version every 5 minutes"
  active: true
  schedule: "@5minutes"
  requirements:
    matchLabels:
      os: "linux"
    matchSelector:
      - { key: "env", operator: "NotIn",  values: ["dev", "testing"] }
  prob:
    kind: http
    spec:
      script: "GET http://localhost:8080/api/v1/version"
