apiVersion: v1
kind: scenarios
metadata:
  name: basic-rest-prober
  labels:
    app: web-prob
    function: front-end
spec:
  description: "Self-prob using HTTP prober"
  active: true
  schedule: "* * * * *"
  script:
    kind: "http/get"
  requirements:
    matchLabels:
      os: "linux"
    matchSelector:
      - { key: "owner", operator: "in",  values: ["trusted", "allowed"] }
      - { key: "env", operator: "notIn",  values: ["dev", "testing"] }
