apiVersion: v1
kind: scenarios
metadata:
  name: rest-httpbin-probe
  labels:
    app: web-prob
    function: front-end
spec:
  description: "HTTP prober checking httpbin every 8 minutes"
  active: true
  schedule: "@8minutes"
  requirements:
    matchLabels:
      env: "dev"
  prob:
    kind: rest
    spec:
      script: |
        # @name Get HTTPBin
        GET https://httpbin.org/get
        Accept: application/json
