apiVersion: v1
kind: scenarios
metadata:
  name: basic-rest-prober
  labels:
    app: web-prob
    function: front-end
spec:
  description: "Self-prob using HTTP prober"
  active: true
  schedule: "* * * * *"
  requirements:
    matchLabels:
      os: "linux"
    matchSelector:
      - { key: "env", operator: "NotIn",  values: ["dev", "testing"] }
  prob:
    kind: tcp
    spec:
      host: localhost
      port: 8080
