#!/usr/bin/env python3
"""Render the Homebrew formula for the CLI from a published stable release.

The tap (sre-norns/homebrew-norns) holds the rendered file. The homebrew-tap
workflow renders it for a release and opens a pull request there, so this
template, not the tap copy, is the source: the next release overwrites any hand
edit in the tap.

The formula installs the release archives themselves rather than building from
source. Homebrew does not quarantine formula downloads, so the unsigned macOS
binaries run without Gatekeeper intervention, and the same file serves Linux.
"""

import argparse
import hashlib
from pathlib import Path
import re
import sys

REPOSITORY = "sre-norns/urth"
BINARY = "urthctl"
CLASS = "Urthctl"
DESC = "Command-line client for Urth synthetic monitoring"
LICENSE = "PolyForm-Noncommercial-1.0.0"
# `--help` exits 0 and needs no API server, profile or network.
HELP_BANNER = "Urth Command line tool"

# Homebrew tracks stable releases only: a prerelease must never reach a tap user.
STABLE_TAG = re.compile(r"v(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)\.(0|[1-9][0-9]*)")
FORMULA_VERSION = re.compile(r'^\s*version "([^"]+)"$', re.MULTILINE)
# Homebrew's platform blocks, each naming the archive GoReleaser built for it.
PLATFORMS = (
    ("on_macos", "on_arm", "darwin", "arm64"),
    ("on_macos", "on_intel", "darwin", "amd64"),
    ("on_linux", "on_arm", "linux", "arm64"),
    ("on_linux", "on_intel", "linux", "amd64"),
)


class FormulaError(Exception):
    pass


def archive_name(tag, os_name, arch):
    return f"{BINARY}_{tag}_{os_name}_{arch}.tar.gz"


def parse_version(text):
    match = STABLE_TAG.fullmatch(text)
    if not match:
        raise FormulaError(f"{text!r} is not a stable release tag (vMAJOR.MINOR.PATCH)")
    return tuple(int(part) for part in match.groups())


def sha256(path):
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for block in iter(lambda: stream.read(1 << 20), b""):
            digest.update(block)
    return digest.hexdigest()


def render(tag, archives):
    """Return the formula for tag, hashing the archives found in archives."""
    parse_version(tag)
    blocks = []
    for os_block in dict.fromkeys(os_block for os_block, *_ in PLATFORMS):
        arch_blocks = []
        for block, arch_block, os_name, arch in PLATFORMS:
            if block != os_block:
                continue
            name = archive_name(tag, os_name, arch)
            path = archives / name
            if not path.is_file():
                raise FormulaError(f"missing release archive {name}")
            arch_blocks.append(
                f"    {arch_block} do\n"
                f'      url "https://github.com/{REPOSITORY}/releases/download/{tag}/{name}"\n'
                f'      sha256 "{sha256(path)}"\n'
                f"    end\n"
            )
        blocks.append(f"  {os_block} do\n" + "\n".join(arch_blocks) + "  end\n")
    platforms = "\n".join(blocks)
    return f"""\
# Generated by https://github.com/{REPOSITORY}/blob/main/scripts/homebrew-formula.py
# for each stable release. Edit the template there: the next release overwrites
# changes made here.
class {CLASS} < Formula
  desc "{DESC}"
  homepage "https://github.com/{REPOSITORY}"
  version "{tag[1:]}"
  license "{LICENSE}"

{platforms}
  def install
    bin.install "{BINARY}"
  end

  test do
    assert_match "{HELP_BANNER}", shell_output("#{{bin}}/{BINARY} --help")
  end
end
"""


def check_upgrade(tag, previous):
    """Refuse to replace a formula with an older release; the same one is a no-op."""
    if not previous.is_file():
        return
    match = FORMULA_VERSION.search(previous.read_text())
    if not match:
        raise FormulaError(f"cannot read the current version from {previous}")
    current = match.group(1)
    if parse_version(tag) < parse_version("v" + current):
        raise FormulaError(f"{previous} already has {current}, newer than {tag}")


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--tag", required=True, help="stable release tag, e.g. v0.1.0")
    parser.add_argument("--archives", required=True, type=Path,
                        help="directory holding the release's CLI archives")
    parser.add_argument("--output", required=True, type=Path,
                        help="formula to write; an existing one must not be newer")
    args = parser.parse_args(argv)
    try:
        check_upgrade(args.tag, args.output)
        formula = render(args.tag, args.archives)
    except FormulaError as error:
        print(f"error: {error}", file=sys.stderr)
        return 1
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(formula)
    return 0


if __name__ == "__main__":
    sys.exit(main())
